workflows:
  mazda_android:
    name: Mazda APK Workflow
    environment:
      flutter: stable
      groups:
        - Mazda 
      android_signing:
        - MazdaKey
    scripts:
      - flutter clean
      - flutter pub get

      - name: Decode Keystore
        script: echo $MAZDA_KEYSTORE | base64 --decode > $MAZDA_KEYSTORE_PATH

      - name: Change Android app name
        script: sed -i.bak "s/android:label=\".*\"/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml

      - name: Change Android package name
        script:
          - flutter pub add change_app_package_name
          - flutter pub run change_app_package_name:main $PACKAGE_NAME

      - name: Change Android icons
        script: cp -r ./ASSETS_FOLDER/$ANDROID_ASSETS_FOLDER/* ./android/app/src/main/res

      - name: Set .env file
        script: echo $DOTENV | base64 --decode > .env

      - flutter build apk --flavor=mazda --dart-define-from-file=.env/mazda.env
    artifacts:
      - build/app/outputs/flutter-apk/app-mazda.apk

  mazda_ios:
    name: Mazda IPA Workflow
    environment:
      flutter: stable
      groups:
        - Mazda 
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --flavor=mazda --dart-define-from-file=.env/mazda.env
    artifacts:
      - build/ios/ipa/*.ipa

  nissan_android:
    name: Nissan APK Workflow
    environment:
      flutter: stable
      groups:
        - Nissan 
      android_signing:
        - NissanKey
    scripts:
      - flutter clean
      - flutter pub get

      - name: Decode Keystore
        script: echo $NISSAN_KEYSTORE | base64 --decode > $NISSAN_KEYSTORE_PATH

      - name: Change Android app name
        script: sed -i.bak "s/android:label=\".*\"/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml

      - name: Change Android package name
        script:
          - flutter pub add change_app_package_name
          - flutter pub run change_app_package_name:main $PACKAGE_NAME

      - name: Change Android icons
        script: cp -r ./ASSETS_FOLDER/$ANDROID_ASSETS_FOLDER/* ./android/app/src/main/res

      - name: Set .env file
        script: echo $DOTENV | base64 --decode > .env

      - flutter build apk --flavor=nissan --dart-define-from-file=.env/nissan.env
    artifacts:
      - build/app/outputs/flutter-apk/app-nissan.apk

  nissan_ios:
    name: Nissan IPA Workflow
    environment:
      flutter: stable
      groups:
        - Nissan 
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --flavor=nissan --dart-define-from-file=.env/nissan.env
    artifacts:
      - build/ios/ipa/*.ipa
